// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/wireframe-library/GrowthAxes.tsx": () => import("../components/mockups/wireframe-library/GrowthAxes.tsx"),
  "./components/mockups/wireframe-library/KnowledgeGraphExample.tsx": () => import("../components/mockups/wireframe-library/KnowledgeGraphExample.tsx"),
  "./components/mockups/wireframe-library/LibrarianPlanDemo.tsx": () => import("../components/mockups/wireframe-library/LibrarianPlanDemo.tsx"),
  "./components/mockups/wireframe-library/PlanRenderer.tsx": () => import("../components/mockups/wireframe-library/PlanRenderer.tsx"),
  "./components/mockups/wireframe-library/TierLadder.tsx": () => import("../components/mockups/wireframe-library/TierLadder.tsx"),
  "./components/mockups/wireframe-library/WorkflowExample.tsx": () => import("../components/mockups/wireframe-library/WorkflowExample.tsx")
};
